2024-06-18 20:20:42,353 - INFO - Login request received
2024-06-18 20:20:42,365 - WARNING - Invalid data received: {'email': [ErrorDetail(string='Enter a valid email address.', code='invalid')]}
2024-06-18 20:20:42,368 - WARNING - Bad Request: /login/
2024-06-18 20:21:12,346 - INFO - Login request received
2024-06-18 20:21:12,366 - INFO - Attempting to authenticate user: watermymelons12345@gmail.com
2024-06-18 20:21:12,798 - INFO - User authenticated successfully
2024-06-18 20:21:32,397 - INFO - Login request received
2024-06-18 20:21:32,417 - INFO - Attempting to authenticate user: watermymelons12345@gmail.com
2024-06-18 20:21:33,007 - INFO - User authenticated successfully
2024-06-18 20:22:01,456 - INFO - Login request received
2024-06-18 20:22:01,479 - INFO - Attempting to authenticate user: newUser@gmail.com
2024-06-18 20:22:02,158 - INFO - User authenticated successfully
2024-06-18 23:00:37,366 - INFO - C:\Users\conno\OneDrive\Desktop\personal files\coding-folders\personal-projects\PathFinder\backend\users\views.py changed, reloading.
2024-06-18 23:40:39,944 - INFO - Login request received
2024-06-18 23:40:39,953 - INFO - Attempting to authenticate user: newUser@gmail.com
2024-06-18 23:40:40,637 - INFO - User authenticated successfully
2024-06-19 12:15:13,270 - WARNING - Unauthorized: /saved/
2024-06-19 12:15:24,500 - INFO - Login request received
2024-06-19 12:15:24,504 - INFO - Attempting to authenticate user: newUser@gmail.com
2024-06-19 12:15:25,072 - INFO - User authenticated successfully
2024-06-19 13:02:33,266 - WARNING - Bad Request: /saved/
2024-06-19 13:03:07,621 - WARNING - Bad Request: /saved/
2024-06-19 13:03:55,057 - WARNING - Bad Request: /saved/
2024-06-19 13:37:25,627 - WARNING - Bad Request: /saved/
2024-06-19 13:37:28,250 - WARNING - Bad Request: /saved/
2024-06-19 13:40:08,980 - WARNING - Bad Request: /saved/
2024-06-19 13:41:21,197 - WARNING - Bad Request: /saved/
2024-06-19 13:41:34,441 - WARNING - Bad Request: /saved/
2024-06-19 13:41:49,317 - WARNING - Bad Request: /saved/
2024-06-19 17:29:19,181 - INFO - Login request received
2024-06-19 17:29:19,197 - INFO - Attempting to authenticate user: watermymelons12345@gmail.com
2024-06-19 17:29:20,332 - INFO - User authenticated successfully
2024-06-19 17:29:27,838 - INFO - Login request received
2024-06-19 17:29:27,846 - INFO - Attempting to authenticate user: watermymelons12345@gmail.com
2024-06-19 17:29:28,620 - INFO - User authenticated successfully
2024-06-20 21:08:25,373 - WARNING - Unauthorized: /saved/
2024-06-20 21:08:35,079 - INFO - Login request received
2024-06-20 21:08:35,079 - INFO - Attempting to authenticate user: newUser@gmail.com
2024-06-20 21:08:35,921 - INFO - User authenticated successfully
2024-06-20 21:08:36,884 - INFO - Login request received
2024-06-20 21:08:36,884 - INFO - Attempting to authenticate user: newUser@gmail.com
2024-06-20 21:08:37,737 - INFO - User authenticated successfully
2024-06-22 23:18:28,710 - WARNING - Unauthorized: /saved/
2024-06-22 23:18:39,088 - INFO - Login request received
2024-06-22 23:18:39,094 - INFO - Attempting to authenticate user: newUser@gmail.com
2024-06-22 23:18:40,752 - INFO - User authenticated successfully
2024-06-22 23:18:40,807 - INFO - Login request received
2024-06-22 23:18:40,807 - INFO - Attempting to authenticate user: newUser@gmail.com
2024-06-22 23:18:43,013 - INFO - User authenticated successfully
2024-06-22 23:20:57,763 - INFO - Login request received
2024-06-22 23:20:57,766 - INFO - Attempting to authenticate user: newUser@gmail.com
2024-06-22 23:20:58,823 - INFO - User authenticated successfully
2024-06-22 23:25:30,812 - INFO - C:\Users\conno\OneDrive\Desktop\personal files\coding-folders\personal-projects\PathFinder\backend\users\views.py changed, reloading.
2024-06-22 23:25:38,382 - INFO - Login request received
2024-06-22 23:25:38,386 - INFO - Attempting to authenticate user: newUser@gmail.com
2024-06-22 23:25:39,169 - INFO - User authenticated successfully
2024-06-22 23:25:52,558 - INFO - Login request received
2024-06-22 23:25:52,558 - INFO - Attempting to authenticate user: newUser@gmail.com
2024-06-22 23:25:53,714 - WARNING - Invalid credentials provided
2024-06-22 23:25:53,724 - WARNING - Bad Request: /login/
2024-06-22 23:26:10,767 - INFO - Login request received
2024-06-22 23:26:10,767 - INFO - Attempting to authenticate user: newUser@gmail.com
2024-06-22 23:26:11,893 - INFO - User authenticated successfully
2024-06-22 23:28:16,234 - INFO - C:\Users\conno\OneDrive\Desktop\personal files\coding-folders\personal-projects\PathFinder\backend\users\views.py changed, reloading.
2024-06-22 23:28:41,431 - INFO - Login request received
2024-06-22 23:28:41,438 - INFO - Attempting to authenticate user: newUser@gmail.com
2024-06-22 23:28:42,221 - INFO - Authentication result: newUser@gmail.com
2024-06-22 23:28:42,221 - INFO - User authenticated successfully
2024-06-22 23:28:42,402 - INFO - Token created successfully
2024-06-22 23:28:42,402 - INFO - Response data prepared: {'user': {'email': 'newUser@gmail.com'}, 'token': 'c0d20077cf62ae846bba22bcfc97b8223136cba0f90a962b2b41e21aa3260931'}
2024-06-22 23:29:39,068 - INFO - C:\Users\conno\OneDrive\Desktop\personal files\coding-folders\personal-projects\PathFinder\backend\users\views.py changed, reloading.
2024-06-22 23:29:44,590 - INFO - Login request received
2024-06-22 23:29:44,594 - INFO - Attempting to authenticate user: newUser@gmail.com
2024-06-22 23:29:45,338 - INFO - Authentication result: newUser@gmail.com
2024-06-22 23:29:45,338 - INFO - User authenticated successfully
2024-06-22 23:29:45,447 - INFO - Token created successfully
2024-06-22 23:29:45,447 - INFO - Response data prepared: {'user': {'email': 'newUser@gmail.com'}, 'token': 'df241d305559744b5b6f384f6f65764323c6b6194d95ae5fc10f8432608d8427'}
2024-06-22 23:30:51,382 - INFO - C:\Users\conno\OneDrive\Desktop\personal files\coding-folders\personal-projects\PathFinder\backend\users\views.py changed, reloading.
2024-06-22 23:31:08,996 - INFO - Login request received
2024-06-22 23:31:09,005 - INFO - Attempting to authenticate user: newUser@gmail.com
2024-06-22 23:31:10,261 - INFO - Authentication result: None
2024-06-22 23:31:10,261 - WARNING - Invalid credentials provided
2024-06-22 23:31:10,268 - WARNING - Bad Request: /login/
2024-06-22 23:31:20,385 - INFO - Login request received
2024-06-22 23:31:20,387 - INFO - Attempting to authenticate user: newUser@gmail.com
2024-06-22 23:31:22,300 - INFO - Authentication result: newUser@gmail.com
2024-06-22 23:31:22,300 - INFO - User authenticated successfully
2024-06-22 23:31:22,375 - INFO - Token created successfully
2024-06-22 23:31:22,400 - INFO - Response data prepared: {'user': {'email': 'newUser@gmail.com'}, 'token': 'e02a79bb7e99756fe24b36ee5da096ee1b55fe4c4e8b0b7a362950606663ac6b'}
2024-06-22 23:31:41,740 - INFO - Login request received
2024-06-22 23:31:41,740 - INFO - Attempting to authenticate user: newUser@gmail.com
2024-06-22 23:31:42,437 - INFO - Authentication result: newUser@gmail.com
2024-06-22 23:31:42,439 - INFO - User authenticated successfully
2024-06-22 23:31:42,450 - INFO - Token created successfully
2024-06-22 23:31:42,450 - INFO - Response data prepared: {'user': {'email': 'newUser@gmail.com'}, 'token': 'bc8d0e7f35b5748438cacdf6db907fe7637c32ea284a0fe3f54497b0c76b85d0'}
2024-06-22 23:35:40,141 - INFO - C:\Users\conno\OneDrive\Desktop\personal files\coding-folders\personal-projects\PathFinder\backend\users\views.py changed, reloading.
2024-06-26 13:01:18,039 - WARNING - Unauthorized: /saved/
2024-06-26 13:01:30,490 - INFO - Login request received
2024-06-26 13:01:30,495 - INFO - Attempting to authenticate user: newUser@gmail.com
2024-06-26 13:01:30,887 - WARNING - Invalid credentials provided
2024-06-26 13:01:30,889 - WARNING - Bad Request: /login/
2024-06-26 13:03:02,272 - WARNING - Bad Request: /register/
2024-06-26 13:04:25,860 - INFO - Login request received
2024-06-26 13:04:25,861 - INFO - Attempting to authenticate user: admin@admin.com
2024-06-26 13:04:26,734 - INFO - User authenticated successfully
2024-06-26 13:04:28,410 - INFO - Login request received
2024-06-26 13:04:28,410 - INFO - Attempting to authenticate user: admin@admin.com
2024-06-26 13:04:29,338 - INFO - User authenticated successfully
2024-06-26 13:08:40,521 - INFO - C:\Users\conno\OneDrive\Desktop\personal files\coding-folders\personal-projects\PathFinder\backend\pathfinderbackend\settings.py changed, reloading.
2024-06-26 13:22:06,114 - WARNING - Unauthorized: /saved/
2024-06-26 13:22:15,999 - INFO - Login request received
2024-06-26 13:22:16,002 - INFO - Attempting to authenticate user: admin@admin.com
2024-06-26 13:22:16,008 - WARNING - Invalid credentials provided
2024-06-26 13:22:16,009 - WARNING - Bad Request: /login/
2024-06-26 13:22:16,794 - INFO - Login request received
2024-06-26 13:22:16,796 - INFO - Attempting to authenticate user: admin@admin.com
2024-06-26 13:22:16,799 - WARNING - Invalid credentials provided
2024-06-26 13:22:16,800 - WARNING - Bad Request: /login/
2024-06-26 13:22:17,954 - INFO - Login request received
2024-06-26 13:22:17,955 - INFO - Attempting to authenticate user: admin@admin.com
2024-06-26 13:22:17,958 - WARNING - Invalid credentials provided
2024-06-26 13:22:17,959 - WARNING - Bad Request: /login/
2024-06-26 13:22:21,380 - INFO - Login request received
2024-06-26 13:22:21,381 - INFO - Attempting to authenticate user: admin@admin.com
2024-06-26 13:22:21,386 - WARNING - Invalid credentials provided
2024-06-26 13:22:21,387 - WARNING - Bad Request: /login/
2024-06-26 13:22:23,079 - INFO - Login request received
2024-06-26 13:22:23,080 - INFO - Attempting to authenticate user: admin@admin.com
2024-06-26 13:22:23,085 - WARNING - Invalid credentials provided
2024-06-26 13:22:23,086 - WARNING - Bad Request: /login/
2024-06-26 13:22:23,511 - INFO - Login request received
2024-06-26 13:22:23,513 - INFO - Attempting to authenticate user: admin@admin.com
2024-06-26 13:22:23,518 - WARNING - Invalid credentials provided
2024-06-26 13:22:23,520 - WARNING - Bad Request: /login/
2024-06-26 13:22:23,871 - INFO - Login request received
2024-06-26 13:22:23,873 - INFO - Attempting to authenticate user: admin@admin.com
2024-06-26 13:22:23,877 - WARNING - Invalid credentials provided
2024-06-26 13:22:23,878 - WARNING - Bad Request: /login/
2024-06-26 13:22:24,203 - INFO - Login request received
2024-06-26 13:22:24,204 - INFO - Attempting to authenticate user: admin@admin.com
2024-06-26 13:22:24,208 - WARNING - Invalid credentials provided
2024-06-26 13:22:24,209 - WARNING - Bad Request: /login/
2024-06-26 13:22:24,371 - INFO - Login request received
2024-06-26 13:22:24,373 - INFO - Attempting to authenticate user: admin@admin.com
2024-06-26 13:22:24,377 - WARNING - Invalid credentials provided
2024-06-26 13:22:24,378 - WARNING - Bad Request: /login/
2024-06-26 13:22:24,594 - INFO - Login request received
2024-06-26 13:22:24,595 - INFO - Attempting to authenticate user: admin@admin.com
2024-06-26 13:22:24,599 - WARNING - Invalid credentials provided
2024-06-26 13:22:24,601 - WARNING - Bad Request: /login/
2024-06-26 13:22:37,102 - INFO - Login request received
2024-06-26 13:22:37,103 - INFO - Attempting to authenticate user: newUser@gmail.com
2024-06-26 13:22:37,928 - INFO - User authenticated successfully
2024-06-26 13:22:38,692 - INFO - Login request received
2024-06-26 13:22:38,693 - INFO - Attempting to authenticate user: newUser@gmail.com
2024-06-26 13:22:39,540 - INFO - User authenticated successfully
2024-06-26 14:48:40,015 - ERROR - Internal Server Error: /saved/62/
Traceback (most recent call last):
  File "C:\Users\conno\OneDrive\Desktop\personal files\coding-folders\personal-projects\PathFinder\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conno\OneDrive\Desktop\personal files\coding-folders\personal-projects\PathFinder\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conno\OneDrive\Desktop\personal files\coding-folders\personal-projects\PathFinder\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conno\OneDrive\Desktop\personal files\coding-folders\personal-projects\PathFinder\backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conno\OneDrive\Desktop\personal files\coding-folders\personal-projects\PathFinder\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conno\OneDrive\Desktop\personal files\coding-folders\personal-projects\PathFinder\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\conno\OneDrive\Desktop\personal files\coding-folders\personal-projects\PathFinder\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\conno\OneDrive\Desktop\personal files\coding-folders\personal-projects\PathFinder\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conno\OneDrive\Desktop\personal files\coding-folders\personal-projects\PathFinder\backend\users\views.py", line 119, in retrieve
    saved = self.queryset.get(pk=pk)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\conno\OneDrive\Desktop\personal files\coding-folders\personal-projects\PathFinder\backend\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
users.models.SavedInfo.DoesNotExist: SavedInfo matching query does not exist.
